config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'

  resources :games

  root 'landing#index'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    validates :name, presence: true, length: { minimum: 1 }
end

app/models/player.rb
class Player < ApplicationRecord
    validates :name, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    def index
        @games = Game.all
    end

    def show
        @game = Game.find(params[:id])
    end

    def new
        @game = Game.new
    end

    def edit
        @game = Game.find(params[:id])
    end

    def create
        @game = Game.new(game_params)

        if @game.save
            redirect_to @game
        else
            render 'new'
        end
    end

    def update
        @game = Game.find(params[:id])

        if @game.update(game_params)
            redirect_to @game
        else
            render 'edit'
        end
    end

    def destroy
        @game = Game.find(params[:id])
        @game.destroy
        redirect_to games_path
    end
end

private
def game_params
    params.require(:game).permit(:name)
end

def user_params
    params..require(:user).permit(:name)
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/games/_form.html.erb
<%= form_with(model: @game, local: true) do |form| %>
 
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@game.errors.count, "error") %> prohibited
        this game from being saved:
      </h2>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/games/edit.html.erb
<h1>Edit game</h1>
 
<%= render 'form' %>

app/views/games/index.html.erb
<h1>Game History</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Id</th>
    <th colspan="2"></th>
  </tr>
 
  <% @games.each do |game| %>
    <tr>
      <td><%= game.name %></td>
      <td><%= game.id %></td>
      <td><%= link_to 'Show', game_path(game) %> | </td>
      <td><%= link_to 'Edit', edit_game_path(game) %> | </td>
      <td><%= link_to 'Delete', game_path(game),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

app/views/games/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Id:</strong>
  <%= @game.id %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %>

app/views/landing/index.html.erb
<h1>MAFAI</h1>
<%= link_to 'New Game', new_game_path %><br><br>
<%= link_to 'Game History', controller: 'games' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MafAI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>